# -*- coding: utf-8 -*-
"""Binary and Multiclass Classification

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OM9Zm2rXWIJqgaw4dbfZkx5xCU8w8xJy
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
from matplotlib import pyplot as plt
# %matplotlib inline
from google.colab import files
  
  
uploaded = files.upload()

df = pd.read_csv('insurance.csv')
df.head()

# hypothesis: younger people are less likely to buy insurance (assumption)
plt.scatter(df.age, df.bought_insurance, marker='+', color='blue')

# split data set
df.shape

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df[['age']], df.bought_insurance, test_size=0.1)

X_test

X_train

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

model.fit(X_train, y_train)

#ages are 47 49 and 61 so it is returning 1 1 and 1. 
model.predict(X_test)

#Perfect model (data size is very small)
model.score(X_test, y_test)