# -*- coding: utf-8 -*-
"""Learning Linear Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kGhvZoMJWlQmOx2U1n7vUGk_22pIZnga
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from google.colab import files
  
  
uploaded = files.upload()

df = pd.read_csv("homeprices.csv")
df.head()

# Commented out IPython magic to ensure Python compatibility.
#making a scatter plot to plot area and price

# %matplotlib inline
plt.xlabel('area(sqr ft)')
plt.ylabel('price(USD$)')
plt.scatter(df.area, df.price, color='green', marker='+')

#begin linerar regression

reg = linear_model.LinearRegression()
reg.fit(df[['area']], df.price)
reg.predict([[3300]])

# Y = mx + b price = m * area + b

reg.coef_ #m

reg.intercept_ #y

135.78767123*3300+180616.43835616432

uploadedAreas = files.upload()

areaDf = pd.read_csv('area.csv')

areaDf.head()

price_prediction = reg.predict(areaDf)

areaDf['prices'] = price_prediction

areaDf

##### BEGIN MULTIVARIATE REGRESSION

#as the home gets older, the price goes down
#even if the house is big, its old, thus the price will shoot down
# price(dependent variable) = m1 * area + m2 * bedrooms + m3 * age + b (area, roooms, age are independent variables)

uploadedMultivariate = files.upload()

mvdf = pd.read_csv('homeprices2.csv')
#mv = multivariate df = dataframe

mvdf.head()

# data preprocessing for handling the missing value in 2. we will find the median

import math
median_bedrooms = math.floor(mvdf.bedrooms.median())
median_bedrooms

mvdf.bedrooms = mvdf.bedrooms.fillna(median_bedrooms)
mvdf

mvreg = linear_model.LinearRegression()
mvreg.fit(mvdf[['area', 'bedrooms', 'age']], mvdf.price)

mvreg.coef_

mvreg.predict([[3000, 4, 40]])
#cheaper because old

mvreg.predict([[3000, 4, 10]])
#more expensive because 30 years newer



